<a href="https://colab.research.google.com/github/pluieciel/applied-ml-uni-lu/blob/master/Ants.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

An ant leaves its anthill in order to forage for food. It moves with the speed of 10cm per second, but it doesn’t know where to go, therefore every second it moves randomly 10cm directly north, south, east or west with equal probability.

1. If the food is located on east-west lines 20cm to the north and 20cm to the south, as well as on north-south lines 20cm to the east and 20cm to the west from the anthill, how long will it take the ant to reach it on average?

In [ ]:
# Discrete phase-type distribution (https://en.wikipedia.org/wiki/Discrete_phase-type_distribution)
# let 10cm be 1 unit, ant at (0,0)
# we denote {(0,0)} as state0, {(0,1), (1,0), (-1,0), (0,-1)} as state 1, {(1,1), (1,-1), (-1,1), (-1,-1)} as state 2, (transient states)
# all other locations as state 3 (absorbing state)

# build transition matrix with transient states
import numpy as np
T = np.matrix([[0,1,0],[1/4,0,1/2],[0,1/2,0]])

init = np.array([1,0,0]) # begin distribution
ones = np.array([1,1,1])
I = np.eye(3)

# the probability density of steps to reach absorbing state (state 3) forms a geometric distribution, the expectation of which is 1/(1-p):
init @ (I-T).I @ ones
# the expectation is 4.5 seconds

matrix([[4.5]])

2. What is the average time the ant will reach food if it is located only on a diagonal line passing through (10cm, 0cm) and (0cm, 10cm) points?

Since symmetric on x and y, we transfer the problem into 1-d random walk to reach 1 from 0 on Z line.

Probability of reach 1 for the first time in 2k+1 step is
$\frac{1}{k+1}C_{k}^{2k}(\frac{1}{2})^{2k+1}$, probability in 2k step is 0.


$\mathop{\mathbb{E}(n) = }\sum_{n=0}^{+\infty} n*p(n) = \sum_{k=0}^{+\infty} (2k+1)*\frac{1}{k+1}C_{k}^{2k}(\frac{1}{2})^{2k+1} = \sum_{k=1}^{+\infty}\frac{(2k-1)!!}{(2k)!!} $

$ \because \frac{(2k-1)!!}{(2k)!!} > \frac{1}{2k} $

$ \therefore \mathop{\mathbb{E}(n)} > \frac{1}{2}\sum_{k=1}^{+\infty}\frac{1}{k} = \infty$

So the average time is infinity

3. Can you write a program that comes up with an estimate of average time to find food for any closed boundary around the anthill? What would be the answer if food is located outside an area defined by ( (x – 2.5cm) / 30cm )2 + ( (y – 2.5cm) / 40cm )2 < 1 in coordinate system where the anthill is located at (x = 0cm, y = 0cm)?

In [ ]:
# define a function
f = lambda pos: ((pos[0]-0.25)/3)**2+((pos[1]-0.25)/40)**2<1

In [ ]:
def rw(f,n):
    sum = 0
    for _ in range(n):
        step = 0
        ant = np.array([0,0])
        while f(ant):
            ant += ([0,1],[0,-1],[-1,0],[1,0])[np.random.randint(4)]
            step += 1
        sum += step
    return sum / n

It is possible to use parallel computing (e.g. Spark on cluster to speed up the simulation)

In [ ]:
rw(f, 100000)

24.00063

With 100000 times trials, the estimated average time is 24 seconds.

In [ ]:
import numpy as np

In [ ]:
T=np.zeros([10,10])

In [ ]:
T

array([[0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.25, 0.  , 0.25, 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [ ]:
T1=T[:-1,:-1]

In [ ]:
T1

array([[0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  ],
       [0.25, 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.25, 0.  , 0.25, 0.  , 0.25, 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.  , 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.25, 0.  , 0.  , 0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  , 0.25],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25, 0.  ]])

In [ ]:
init = np.zeros(9)

In [ ]:
init[4]=1

In [ ]:
init

array([0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [ ]:
ones = np.ones(9)

In [ ]:
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
I = np.eye(9)

In [ ]:
init @ (I-np.matrix(T1)).I @ ones

matrix([[4.5]])

In [ ]:
T = np.matrix([[0,1,0],[1/4,0,1/2],[0,1/2,0]])